// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2E4zEmuHckdewqtXsYGyUuACCq7zxzE',
    appId: '1:935634339612:web:5bd38dd9bed304e4745cd9',
    messagingSenderId: '935634339612',
    projectId: 'expense-manager-345a7',
    authDomain: 'expense-manager-345a7.firebaseapp.com',
    storageBucket: 'expense-manager-345a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_cV8gBEPM6TnUf1SIg50r8MJBqR5lh4',
    appId: '1:935634339612:android:c99a74397cfec549745cd9',
    messagingSenderId: '935634339612',
    projectId: 'expense-manager-345a7',
    storageBucket: 'expense-manager-345a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFz08mnohip0GNYFQeN8kokFsTbhEhwlI',
    appId: '1:935634339612:ios:0af60a4e95235ce3745cd9',
    messagingSenderId: '935634339612',
    projectId: 'expense-manager-345a7',
    storageBucket: 'expense-manager-345a7.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFz08mnohip0GNYFQeN8kokFsTbhEhwlI',
    appId: '1:935634339612:ios:0af60a4e95235ce3745cd9',
    messagingSenderId: '935634339612',
    projectId: 'expense-manager-345a7',
    storageBucket: 'expense-manager-345a7.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz2E4zEmuHckdewqtXsYGyUuACCq7zxzE',
    appId: '1:935634339612:web:742fbcb23c0c519c745cd9',
    messagingSenderId: '935634339612',
    projectId: 'expense-manager-345a7',
    authDomain: 'expense-manager-345a7.firebaseapp.com',
    storageBucket: 'expense-manager-345a7.firebasestorage.app',
  );
}
